#!/bin/bash

############################################################
# Messages

red="\033[0;31m"
green="\033[0;32m"
yellow="\033[0;33m"
no_color="\033[0m"

check="${green}CHECK${no_color}"
success="${green}SUCCESS${no_color}"
done="${green}Done${no_color}"
ok="${green}ok${no_color}"

error="${red}ERROR${no_color}"

function print_eof {
	if [ -n "$1" ] ; then
		echo -e "$1"
	else
	    while read -r line ; do
    	    echo -e "$line"
	    done < /dev/stdin
	fi
}

function warning {
    >&2 printf "${yellow}"
    >&2 print_eof "$1"
    >&2 printf "${no_color}"
}
